# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_auto_20160923_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('THEATRE', 'Theatre'), ('CIRCUS', 'Circus')], default='CONCERT', max_length=7),
        ),
    ]
